#!/usr/bin/env python3
"""Apply a move plan generated by generate_move_plan.py.

Moves files according to the plan CSV.  Supports three modes:
  --mode move           — Move files to the specified target directory (default)
  --mode trash          — Move files to macOS Trash using Finder (safer, recoverable)
  --mode photos-trash   — Move Photos.app managed files to "Recently Deleted"
                          via AppleScript (keeps Photos library consistent)

Safety guarantees:
  - No files are ever permanently deleted
  - If target exists, the move is skipped
  - All operations are logged to move_log.csv
  - In trash mode, files go to macOS Trash and can be restored via Finder
  - In photos-trash mode, photos go to Photos.app "Recently Deleted" (30-day recovery)
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime

# Shared AppleScript escaping (single source of truth)
from applescript_utils import escape_applescript as _escape_applescript


# ---------------------------------------------------------------------------
# Automation permission management for Photos.app
# ---------------------------------------------------------------------------

def _ensure_photos_running() -> bool:
    """Launch Photos.app if not already running.

    The `activate` Apple Event is exempt from automation permission checks,
    so this always works.  Returns True if Photos.app is running.
    """
    try:
        subprocess.run(
            ["/usr/bin/osascript", "-e",
             'tell application "Photos" to activate'],
            capture_output=True, text=True, timeout=15,
        )
        time.sleep(2)  # wait for Photos to fully start
        return True
    except Exception:
        return False


def _check_photos_automation_permission() -> str:
    """Check whether automation permission for Photos.app has been granted.

    Returns one of: "granted", "denied", "sandboxed", "not_running", "error".
    """
    script = '''
tell application "Photos"
    try
        set c to count of albums
        return "granted"
    on error errMsg number errorNumber
        if errorNumber is -1743 then
            return "denied"
        else if errorNumber is -10004 then
            return "sandboxed"
        else if errorNumber is -600 then
            return "not_running"
        else
            return "error:" & errorNumber
        end if
    end try
end tell
'''
    try:
        result = subprocess.run(
            ["/usr/bin/osascript", "-s", "o", "-e", script],
            capture_output=True, text=True, timeout=15,
        )
        output = result.stdout.strip()
        if output.startswith("granted"):
            return "granted"
        elif output.startswith("denied"):
            return "denied"
        elif output.startswith("sandboxed"):
            return "sandboxed"
        elif output.startswith("not_running"):
            return "not_running"
        return "error"
    except Exception:
        return "error"


def _request_photos_automation_permission() -> bool:
    """Attempt to trigger the automation permission dialog for Photos.app.

    Sends a read-only Apple Event (`count of albums`) which causes macOS to
    show the system permission dialog on first use.  Returns True if
    permission is now granted.
    """
    # Make sure Photos.app is running first
    _ensure_photos_running()

    print()
    print("  🔐 首次使用 Photos.app 自动化功能，需要授权。")
    print("  如果弹出系统对话框，请点击「允许」/「OK」。")
    print("  If a system dialog appears, click \"Allow\" / \"OK\".")
    print()

    # Send a read-only command to trigger the permission dialog
    result = subprocess.run(
        ["/usr/bin/osascript", "-e",
         'tell application "Photos" to count of albums'],
        capture_output=True, text=True, timeout=30,
    )

    if result.returncode == 0:
        print("  ✅ 自动化权限已授予 / Automation permission granted.")
        return True
    elif "-1743" in result.stderr:
        print("  ❌ 权限被拒绝 / Permission denied.")
        _print_permission_instructions()
        return False
    elif "-600" in result.stderr:
        print("  ⚠️  Photos.app 未运行，请重试 / Photos.app not running, please retry.")
        return False
    else:
        print(f"  ⚠️  未知错误 / Unknown error: {result.stderr.strip()}")
        return False


def _print_permission_instructions() -> None:
    """Print step-by-step instructions for manually granting automation permission."""
    print()
    print("  ╔══════════════════════════════════════════════════════════╗")
    print("  ║  手动授权 Photos.app 自动化权限 / Manual Authorization  ║")
    print("  ╠══════════════════════════════════════════════════════════╣")
    print("  ║                                                          ║")
    print("  ║  1. 打开「系统设置」>「隐私与安全性」>「自动化」       ║")
    print("  ║     System Settings > Privacy & Security > Automation   ║")
    print("  ║                                                          ║")
    print("  ║  2. 找到你运行此脚本的终端应用                          ║")
    print("  ║     (Terminal.app / iTerm2 / VSCode 等)                 ║")
    print("  ║                                                          ║")
    print("  ║  3. 勾选该应用下 Photos 旁边的复选框                    ║")
    print("  ║     Check the box next to Photos under your terminal    ║")
    print("  ║                                                          ║")
    print("  ║  4. 如果列表中没有出现：                                ║")
    print("  ║     - 先运行一次此脚本触发权限请求                      ║")
    print("  ║     - 或在终端执行: tccutil reset AppleEvents           ║")
    print("  ║       (重置后重新运行脚本即可再次弹出授权对话框)        ║")
    print("  ║                                                          ║")
    print("  ╚══════════════════════════════════════════════════════════╝")
    print()


def ensure_photos_permission() -> bool:
    """High-level entry: ensure Photos.app automation permission is granted.

    1. Check if already granted.
    2. If not, launch Photos.app and request permission.
    3. If denied or sandboxed, print manual instructions and return False.

    Returns True if permission is available.
    """
    status = _check_photos_automation_permission()

    if status == "granted":
        return True

    if status == "not_running":
        print("  📸 正在启动 Photos.app / Launching Photos.app...")
        _ensure_photos_running()
        status = _check_photos_automation_permission()
        if status == "granted":
            return True

    if status == "denied":
        print("  ❌ Photos.app 自动化权限已被拒绝 / Automation permission denied.")
        _print_permission_instructions()
        return False

    if status == "sandboxed":
        print("  ⚠️  当前运行环境限制了对 Photos.app 的访问。")
        print("     Current environment restricts access to Photos.app.")
        print("     请在终端 (Terminal.app) 中运行此脚本。")
        print("     Please run this script from Terminal.app instead.")
        print()
        return False

    # Not yet granted — try to request (will trigger the system dialog)
    return _request_photos_automation_permission()


# ---------------------------------------------------------------------------
# File operations
# ---------------------------------------------------------------------------

def move_to_trash(path: str) -> tuple:
    """Move a file to macOS Trash using osascript (Finder).  Returns (success, message)."""
    try:
        esc_path = _escape_applescript(path)
        result = subprocess.run(
            ["/usr/bin/osascript", "-e",
             f'tell application "Finder" to delete POSIX file "{esc_path}"'],
            capture_output=True, text=True, timeout=30,
        )
        if result.returncode == 0:
            return True, ""
        else:
            return False, f"Finder error: {result.stderr.strip()}"
    except Exception as e:
        return False, str(e)


def move_photos_to_trash(file_paths: list) -> tuple:
    """Move Photos.app managed files to "Recently Deleted" via AppleScript.

    Uses osascript to send Apple Events to Photos.app.  This is the
    recommended approach because osascript is an Apple-signed system binary
    that reliably triggers the macOS automation permission dialog.

    The deletion flow uses `spotlight` to select each photo, then sends
    Cmd+Delete to move it to Photos.app's "Recently Deleted" album.
    Photos can be recovered for 30 days from "Recently Deleted".

    If the automation permission is denied after requesting, falls back to
    generating a .applescript file for the user to run manually.

    Returns (success_count, error_count, messages, deleted_filenames).
    """
    if not file_paths:
        return 0, 0, ["No files to process"], set()

    # Step 1: Ensure we have automation permission
    if not ensure_photos_permission():
        # Permission denied — generate a .applescript file for manual execution
        return _fallback_applescript(file_paths)

    # Step 2: Ensure Photos.app is running
    _ensure_photos_running()

    # Step 3: Build UUID→path mapping for matching
    # Photos.app AppleScript `id` property returns "{UUID}/L0/001"
    # Our scan DB `filename` is "{UUID}.{ext}" (the UUID-based filename)
    # We extract UUID from the filename (strip extension) to match
    target_uuids = {}  # UUID → file_path
    for fp in file_paths:
        basename = os.path.basename(fp)
        # Extract UUID: "46CF7286-889C-4AB0-80E5-57F8B31F1547.jpeg" → "46CF7286-889C-4AB0-80E5-57F8B31F1547"
        uuid_part = os.path.splitext(basename)[0]
        if len(uuid_part) >= 32:  # Valid UUID format
            target_uuids[uuid_part] = fp

    # Step 4: Delete each matching photo using spotlight + Cmd+Delete
    # This is the only reliable method: Photos.app's `delete` AppleScript
    # command fails with -10000, but spotlight + GUI scripting works.
    success = 0
    errors = 0
    messages = []
    deleted_paths = set()  # Track by UUID for reliable matching in apply_plan

    for uuid, fp in target_uuids.items():
        # Use Photos.app id format: "{UUID}/L0/001"
        photos_id = f"{uuid}/L0/001"
        delete_script = f'''
tell application "Photos"
    activate
    try
        set theItem to media item id "{photos_id}"
        set theFilename to filename of theItem
        spotlight theItem
        delay 2
        set sel to selection
        set selCount to count of sel

        if selCount > 0 then
            tell application "System Events"
                tell application process "Photos"
                    keystroke (ASCII character 8) using command down
                end tell
            end tell
            delay 2
            tell application "System Events"
                tell application process "Photos"
                    try
                        if (exists sheet 1 of window 1) then
                            click button "删除" of sheet 1 of window 1
                        end if
                    end try
                end tell
            end tell
            return "deleted:" & theFilename
        else
            return "no_selection:" & theFilename
        end if
    on error errMsg
        return "error:" & errMsg
    end try
end tell
'''
        try:
            result = subprocess.run(
                ["/usr/bin/osascript", "-e", delete_script],
                capture_output=True, text=True, timeout=30,
            )
            stdout = result.stdout.strip()
            if result.returncode == 0 and "deleted:" in stdout:
                # Track by UUID for reliable matching in apply_plan
                success += 1
                deleted_paths.add(uuid)
            elif "no_selection:" in stdout:
                errors += 1
                messages.append(f"Could not select photo: {os.path.basename(fp)}")
            else:
                errors += 1
                messages.append(f"Delete failed for {os.path.basename(fp)}: {result.stderr.strip()[:100]}")
        except subprocess.TimeoutExpired:
            errors += 1
            messages.append(f"Timeout deleting {os.path.basename(fp)}")
        except Exception as e:
            errors += 1
            messages.append(f"Error deleting {os.path.basename(fp)}: {e}")

    if success > 0:
        msg = (
            f"✅ {success} photos moved to Photos.app "
            f'"Recently Deleted" (30-day recovery).'
        )
        messages.insert(0, msg)

    return success, errors, messages, deleted_paths


def _fallback_applescript(file_paths: list) -> tuple:
    """Generate a .applescript file for the user to run manually.

    This is used when automation permission is denied or the sandbox blocks
    Apple Events.  The generated AppleScript uses spotlight + Cmd+Delete
    (GUI scripting) to delete photos from Photos.app, which moves them to
    "Recently Deleted" (recoverable for 30 days).

    Returns (0, len(file_paths), [messages], set()) — no items actually deleted,
    but the script file is generated for manual execution.
    """
    if not file_paths:
        return 0, 0, ["No files to process"], set()

    # Build target filename set
    target_filenames = set()
    for fp in file_paths:
        target_filenames.add(os.path.basename(fp))

    # Generate AppleScript using spotlight + Cmd+Delete approach
    # (the `delete` AppleScript command fails with -10000 in Photos.app)
    filename_checks = []
    for fname in sorted(target_filenames):
        escaped = fname.replace('"', '\\"')
        filename_checks.append(f'        if theFilename is "{escaped}" then')

    # Build a script that lists all media items, finds matches, and
    # deletes them using spotlight + GUI scripting
    script = '''\
tell application "Photos"
    activate
    delay 2
    set allItems to media items
    set deletedCount to 0
    repeat with i from 1 to count of allItems
        set theItem to media item i
        try
            set theFilename to filename of theItem
'''
    # Add filename matching
    first = True
    for fname in sorted(target_filenames):
        escaped = fname.replace('"', '\\"')
        if first:
            script += f'            if theFilename is "{escaped}" then\n'
            first = False
        else:
            script += f'            else if theFilename is "{escaped}" then\n'

    script += '''\
                -- Spotlight the photo to select it
                spotlight theItem
                delay 2
                set sel to selection
                if (count of sel) > 0 then
                    -- Use Cmd+Delete to move to Recently Deleted
                    tell application "System Events"
                        tell application process "Photos"
                            keystroke (ASCII character 8) using command down
                        end tell
                    end tell
                    delay 2
                    -- Handle confirmation dialog if it appears
                    tell application "System Events"
                        tell application process "Photos"
                            try
                                if (exists sheet 1 of window 1) then
                                    click button "删除" of sheet 1 of window 1
                                end if
                            end try
                        end tell
                    end tell
                    set deletedCount to deletedCount + 1
                    delay 1
                end if
            end if
        end try
    end repeat
    return deletedCount
end tell
'''

    # Write to a file next to the plan output directory
    import tempfile
    script_path = os.path.join(tempfile.gettempdir(),
                               "snaptidy_photos_trash.applescript")
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)

    msg = (
        f"⚠️  Photos.app 自动化权限不可用 / Automation permission unavailable.\n"
        f"   已生成 AppleScript / Generated: {script_path}\n"
        f"   在终端运行 / Run in Terminal:\n"
        f"     osascript {script_path}\n"
        f"   这将移动 {len(target_filenames)} 张照片到 Photos.app 的"
        f'"最近删除"（30天内可恢复）。\n'
        f'   This will move {len(target_filenames)} photos to Photos.app\'s '
        f'"Recently Deleted" (recoverable for 30 days).'
    )
    _print_permission_instructions()
    return 0, len(target_filenames), [msg], set()


# ---------------------------------------------------------------------------
# Plan application
# ---------------------------------------------------------------------------

def apply_plan(plan_path: str, log_path: str, mode: str = "move"):
    """Apply the move plan.  mode: 'move', 'trash', or 'photos-trash'."""
    log_entries = []
    stats = {"moved": 0, "trashed": 0, "photos_trashed": 0, "skipped": 0, "error": 0}

    # For photos-trash mode, collect all paths first for batch processing
    if mode == "photos-trash":
        photos_paths = []
        with open(plan_path, newline="", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                src = row.get("source_path", "")
                if src and os.path.exists(src):
                    photos_paths.append(src)

        if photos_paths:
            print(f"Processing {len(photos_paths)} files via Photos.app...")
            success, errors, messages, deleted_uuids = move_photos_to_trash(photos_paths)
            stats["photos_trashed"] = success
            stats["error"] = errors
            timestamp = datetime.now().isoformat()
            for path in photos_paths:
                # Extract UUID from filename to match against deleted_uuids
                basename = os.path.basename(path)
                file_uuid = os.path.splitext(basename)[0]
                is_deleted = file_uuid in deleted_uuids
                log_entries.append({
                    "timestamp": timestamp,
                    "action": "photos-trash",
                    "source_path": path,
                    "target_path": "Photos_Recently_Deleted",
                    "reason": "Photos.app managed file",
                    "status": "photos_trashed" if is_deleted else "error",
                    "message": "; ".join(messages) if messages and not is_deleted else "",
                })
        else:
            print("No files to process via Photos.app.")
    else:
        # Standard mode: move or trash
        with open(plan_path, newline="", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                action = row.get("action", "").lower()
                src = row.get("source_path")
                dest = row.get("target_path", "")
                reason = row.get("reason", "")
                timestamp = datetime.now().isoformat()
                status = "skipped"
                msg = ""

                if action not in ("move", "trash"):
                    msg = f"Unsupported action: {action}"
                elif not os.path.exists(src):
                    msg = "source missing"
                elif mode == "trash" or action == "trash" or (dest and "__TRASH__" in dest):
                    # Move to macOS Trash
                    success, err = move_to_trash(src)
                    if success:
                        status = "trashed"
                        stats["trashed"] += 1
                    else:
                        status = "error"
                        msg = err
                        stats["error"] += 1
                else:
                    # Regular move
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    if os.path.exists(dest):
                        msg = "target exists"
                    else:
                        try:
                            shutil.move(src, dest)
                            status = "moved"
                            stats["moved"] += 1
                        except Exception as e:
                            msg = str(e)
                            status = "error"
                            stats["error"] += 1

                if status == "skipped":
                    stats["skipped"] += 1

                log_entries.append({
                    "timestamp": timestamp,
                    "action": action,
                    "source_path": src,
                    "target_path": dest if mode != "trash" else "macOS_Trash",
                    "reason": reason,
                    "status": status,
                    "message": msg,
                })

    # Write log
    with open(log_path, "w", newline="", encoding="utf-8-sig") as lf:
        fieldnames = ["timestamp", "action", "source_path", "target_path", "reason", "status", "message"]
        writer = csv.DictWriter(lf, fieldnames=fieldnames)
        writer.writeheader()
        for entry in log_entries:
            writer.writerow(entry)

    # Print summary
    print(f"Move plan applied.  Log written to {log_path}")
    parts = []
    if stats["moved"]:
        parts.append(f"Moved: {stats['moved']}")
    if stats["trashed"]:
        parts.append(f"Trashed: {stats['trashed']}")
    if stats["photos_trashed"]:
        parts.append(f"Photos → Recently Deleted: {stats['photos_trashed']}")
    parts.append(f"Skipped: {stats['skipped']}")
    parts.append(f"Errors: {stats['error']}")
    print(f"  {'  |  '.join(parts)}")


# ---------------------------------------------------------------------------
# Undo support
# ---------------------------------------------------------------------------

def compute_file_checksum(path: str) -> str:
    """Compute SHA-256 checksum of a file for undo verification."""
    import hashlib
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return ""


def save_undo_record(log_entries: list, plan_path: str) -> str:
    """Save undo record for the most recent operation.

    Undo records are stored in the same directory as the plan file,
    under an undo_records/ subdirectory. Each record is a JSON file
    containing all source/destination mappings and file checksums.

    Returns the path to the undo record file.
    """
    undo_dir = os.path.join(os.path.dirname(plan_path), "undo_records")
    os.makedirs(undo_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    undo_path = os.path.join(undo_dir, f"undo_{timestamp}.json")

    # Build undo record
    record = {
        "created_at": datetime.now().isoformat(),
        "expires_at": (datetime.now() + __import__("datetime").timedelta(days=30)).isoformat(),
        "plan_file": os.path.basename(plan_path),
        "operations": [],
    }

    for entry in log_entries:
        if entry.get("status") in ("moved", "trashed"):
            op = {
                "source_path": entry.get("source_path", ""),
                "target_path": entry.get("target_path", ""),
                "action": entry.get("action", ""),
                "status": entry.get("status", ""),
            }
            record["operations"].append(op)

    with open(undo_path, "w", encoding="utf-8") as f:
        __import__("json").dump(record, f, indent=2, ensure_ascii=False)

    return undo_path


def undo_last(plan_dir: str) -> None:
    """Undo the most recent move operation.

    Reads the latest undo record and reverses all operations.
    """
    import json as json_mod

    undo_dir = os.path.join(plan_dir, "undo_records")
    if not os.path.isdir(undo_dir):
        print("No undo records found.")
        return

    # Find latest undo record
    undo_files = sorted(
        [f for f in os.listdir(undo_dir) if f.startswith("undo_") and f.endswith(".json")],
        reverse=True
    )

    if not undo_files:
        print("No undo records found.")
        return

    latest = os.path.join(undo_dir, undo_files[0])
    with open(latest, encoding="utf-8") as f:
        record = json_mod.load(f)

    # Check expiry
    expires = record.get("expires_at", "")
    if expires:
        try:
            exp_dt = datetime.fromisoformat(expires)
            if datetime.now() > exp_dt:
                print(f"⚠️  Undo record expired on {expires}")
                print("   The original files may have been modified. Proceed with caution.")
        except ValueError:
            pass

    ops = record.get("operations", [])
    if not ops:
        print("Undo record contains no operations.")
        return

    print(f"Undo record: {undo_files[0]}")
    print(f"  Created: {record.get('created_at', 'unknown')}")
    print(f"  Operations: {len(ops)}")
    print()

    reversed_count = 0
    error_count = 0

    for op in reversed(ops):  # Reverse order: undo last operation first
        src = op.get("source_path", "")
        dest = op.get("target_path", "")
        status = op.get("status", "")

        if status == "moved" and dest and os.path.exists(dest):
            # Move file back
            try:
                os.makedirs(os.path.dirname(src), exist_ok=True)
                if not os.path.exists(src):
                    shutil.move(dest, src)
                    reversed_count += 1
                else:
                    error_count += 1
            except Exception as e:
                print(f"  ❌ Failed to undo {dest} → {src}: {e}")
                error_count += 1
        elif status == "trashed":
            # Cannot undo macOS Trash from CLI — user must use Finder > Put Back
            print(f"  ⚠️  Cannot undo Trash for {src} — use Finder > Put Back")

    # Remove the undo record after successful undo
    if error_count == 0:
        os.remove(latest)
        print(f"✅ Undone {reversed_count} operations. Undo record removed.")
    else:
        print(f"⚠️  Undone {reversed_count}/{len(ops)} operations. {error_count} errors.")
        print(f"   Undo record kept: {latest}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a move plan for duplicate files (safe: move or trash)")
    parser.add_argument("--plan", required=True, help="Path to move_plan.csv")
    parser.add_argument("--mode", choices=["move", "trash", "photos-trash"], default="move",
                        help="Action mode: 'move' to review folder, 'trash' to macOS Trash, "
                             "'photos-trash' for Photos.app Recently Deleted (default: move)")
    parser.add_argument("--undo", action="store_true",
                        help="Undo the most recent move operation")
    args = parser.parse_args()
    plan_path = os.path.abspath(args.plan)
    log_path = os.path.join(os.path.dirname(plan_path), "move_log.csv")

    # Undo mode
    if args.undo:
        plan_dir = os.path.dirname(plan_path)
        # If plan file doesn't exist but directory does, use directory
        if not os.path.isfile(plan_path) and os.path.isdir(plan_dir):
            undo_last(plan_dir)
        else:
            undo_last(os.path.dirname(plan_path))
        return

    print(f"⚠️  About to apply move plan: {plan_path}")
    print(f"   Mode: {args.mode}")
    if args.mode == "trash":
        print("   Files will be moved to macOS Trash (recoverable via Finder)")
    elif args.mode == "photos-trash":
        print("   Photos will be moved to Photos.app \"Recently Deleted\" (30-day recovery)")
        print("   首次使用会弹出授权对话框 / First use will show a permission dialog")
    else:
        print("   Files will be moved to review folder (NOT deleted)")
    print()

    apply_plan(plan_path, log_path, mode=args.mode)

    # Save undo record for non-undo operations
    if not args.undo:
        try:
            from apply_move_plan import save_undo_record
            # Re-read log entries to build undo record
            log_entries_for_undo = []
            with open(log_path, newline="", encoding="utf-8-sig") as lf:
                reader = csv.DictReader(lf)
                for row in reader:
                    log_entries_for_undo.append(row)
            undo_path = save_undo_record(log_entries_for_undo, plan_path)
            print(f"  Undo record saved: {undo_path}")
            print(f"  To undo: python3 scripts/apply_move_plan.py --plan {plan_path} --undo")
        except Exception as e:
            print(f"  ⚠️  Could not save undo record: {e}")


if __name__ == "__main__":
    main()
