#!/usr/bin/env python3
"""Apply a move plan generated by generate_move_plan.py.

Moves files according to the plan CSV.  Supports two modes:
  --mode move    — Move files to the specified target directory (default)
  --mode trash   — Move files to macOS Trash using Finder (safer, recoverable)

Safety guarantees:
  - No files are ever permanently deleted
  - If target exists, the move is skipped
  - All operations are logged to move_log.csv
  - In trash mode, files go to macOS Trash and can be restored via Finder
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
from datetime import datetime


def move_to_trash(path: str) -> tuple:
    """Move a file to macOS Trash using osascript (Finder).  Returns (success, message)."""
    try:
        # Use macOS osascript to move to Trash via Finder
        result = subprocess.run(
            ["osascript", "-e", f'tell application "Finder" to delete POSIX file "{path}"'],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return True, ""
        else:
            return False, f"Finder error: {result.stderr.strip()}"
    except Exception as e:
        return False, str(e)


def apply_plan(plan_path: str, log_path: str, mode: str = "move"):
    """Apply the move plan.  mode: 'move' or 'trash'."""
    log_entries = []
    stats = {"moved": 0, "trashed": 0, "skipped": 0, "error": 0}

    with open(plan_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        for row in reader:
            action = row.get("action", "").lower()
            src = row.get("source_path")
            dest = row.get("target_path", "")
            reason = row.get("reason", "")
            timestamp = datetime.now().isoformat()
            status = "skipped"
            msg = ""

            if action not in ("move", "trash"):
                msg = f"Unsupported action: {action}"
            elif not os.path.exists(src):
                msg = "source missing"
            elif mode == "trash" or action == "trash" or (dest and "__TRASH__" in dest):
                # Move to macOS Trash
                success, err = move_to_trash(src)
                if success:
                    status = "trashed"
                    stats["trashed"] += 1
                else:
                    status = "error"
                    msg = err
                    stats["error"] += 1
            else:
                # Regular move
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                if os.path.exists(dest):
                    msg = "target exists"
                    stats["skipped"] += 1
                else:
                    try:
                        shutil.move(src, dest)
                        status = "moved"
                        stats["moved"] += 1
                    except Exception as e:
                        msg = str(e)
                        status = "error"
                        stats["error"] += 1

            if status == "skipped":
                stats["skipped"] += 1

            log_entries.append({
                "timestamp": timestamp,
                "action": action,
                "source_path": src,
                "target_path": dest if mode != "trash" else "macOS_Trash",
                "reason": reason,
                "status": status,
                "message": msg,
            })

    # Write log
    with open(log_path, "w", newline="", encoding="utf-8-sig") as lf:
        fieldnames = ["timestamp", "action", "source_path", "target_path", "reason", "status", "message"]
        writer = csv.DictWriter(lf, fieldnames=fieldnames)
        writer.writeheader()
        for entry in log_entries:
            writer.writerow(entry)

    # Print summary
    print(f"Move plan applied.  Log written to {log_path}")
    print(f"  Moved: {stats['moved']}  |  Trashed: {stats['trashed']}  |  Skipped: {stats['skipped']}  |  Errors: {stats['error']}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a move plan for duplicate files (safe: move or trash)")
    parser.add_argument("--plan", required=True, help="Path to move_plan.csv")
    parser.add_argument("--mode", choices=["move", "trash"], default="move",
                        help="Action mode: 'move' to review folder, 'trash' to macOS Trash (default: move)")
    args = parser.parse_args()
    plan_path = os.path.abspath(args.plan)
    log_path = os.path.join(os.path.dirname(plan_path), "move_log.csv")

    print(f"⚠️  About to apply move plan: {plan_path}")
    print(f"   Mode: {args.mode}")
    if args.mode == "trash":
        print("   Files will be moved to macOS Trash (recoverable via Finder)")
    else:
        print("   Files will be moved to review folder (NOT deleted)")
    print()

    apply_plan(plan_path, log_path, mode=args.mode)


if __name__ == "__main__":
    main()
