#!/usr/bin/env python3
"""Apply a move plan generated by generate_move_plan.py.

Moves files according to the plan CSV.  Supports three modes:
  --mode move           — Move files to the specified target directory (default)
  --mode trash          — Move files to macOS Trash using Finder (safer, recoverable)
  --mode photos-trash   — Move Photos.app managed files to Trash via PyObjC
                          (keeps Photos library consistent)

Safety guarantees:
  - No files are ever permanently deleted
  - If target exists, the move is skipped
  - All operations are logged to move_log.csv
  - In trash mode, files go to macOS Trash and can be restored via Finder
  - In photos-trash mode, PyObjC is used to properly remove from Photos.app
"""

import argparse
import csv
import os
import shutil
import subprocess
import sys
from datetime import datetime

# Check for PyObjC availability (optional, for Photos.app integration)
PYOBJC_AVAILABLE = False
try:
    import objc
    PYOBJC_AVAILABLE = True
except ImportError:
    pass


def move_to_trash(path: str) -> tuple:
    """Move a file to macOS Trash using osascript (Finder).  Returns (success, message)."""
    try:
        result = subprocess.run(
            ["osascript", "-e", f'tell application "Finder" to delete POSIX file "{path}"'],
            capture_output=True, text=True, timeout=30
        )
        if result.returncode == 0:
            return True, ""
        else:
            return False, f"Finder error: {result.stderr.strip()}"
    except Exception as e:
        return False, str(e)


def move_photos_to_trash(file_paths: list) -> tuple:
    """Move Photos.app managed files to Trash via PyObjC.

    Uses Photos.app's scripting bridge to properly remove photos,
    keeping the library database consistent.  Photos are moved to
    Photos.app's "Recently Deleted" album (recoverable for 30 days).

    If PyObjC/ScriptingBridge fails (permission issues), falls back to
    generating a .applescript file for the user to run manually.

    Returns (success_count, error_count, messages, deleted_filenames).
    """
    if not PYOBJC_AVAILABLE:
        return _fallback_applescript(file_paths)

    try:
        from ScriptingBridge import SBApplication
        photos_app = SBApplication.applicationWithBundleIdentifier_("com.apple.Photos")

        if photos_app is None:
            return _fallback_applescript(file_paths)

        # Activate Photos.app
        try:
            photos_app.activate()
        except Exception:
            pass

        success = 0
        errors = 0
        messages = []
        deleted_filenames = set()

        # Build a set of target filenames for quick lookup
        target_filenames = set()
        for fp in file_paths:
            target_filenames.add(os.path.basename(fp))

        # Get the media items
        media_items = photos_app.mediaItems()
        if media_items is None:
            return _fallback_applescript(file_paths)

        # Check if we actually got items (permission may return empty)
        try:
            item_count = media_items.count()
            if item_count is None or item_count == 0:
                # Try array() as alternative
                arr = media_items.array()
                if arr is None or len(arr) == 0:
                    return _fallback_applescript(file_paths)
        except Exception:
            return _fallback_applescript(file_paths)

        # Find and delete matching items
        items_to_delete = []
        try:
            for item in media_items():
                try:
                    item_path = item.path()
                    if item_path and os.path.basename(item_path) in target_filenames:
                        items_to_delete.append(item)
                except Exception:
                    continue
        except Exception:
            return _fallback_applescript(file_paths)

        if not items_to_delete:
            return _fallback_applescript(file_paths)

        # Delete items (moves to Recently Deleted in Photos.app)
        for item in items_to_delete:
            try:
                item.delete()
                success += 1
                try:
                    deleted_filenames.add(item.name())
                except Exception:
                    pass
            except Exception as e:
                errors += 1
                try:
                    name = item.name()
                except Exception:
                    name = "unknown"
                messages.append(f"Error deleting {name}: {e}")

        return success, errors, messages, deleted_filenames

    except Exception as e:
        return _fallback_applescript(file_paths)


def _fallback_applescript(file_paths: list) -> tuple:
    """Generate a .applescript file for the user to run manually.

    This is used when ScriptingBridge fails (permission issues on macOS).
    The generated AppleScript will delete the specified photos from
    Photos.app, moving them to "Recently Deleted" (recoverable for 30 days).

    Returns (0, len(file_paths), [messages], set()) — no items actually deleted,
    but the script file is generated for manual execution.
    """
    if not file_paths:
        return 0, 0, ["No files to process"], set()

    # Build target path set
    target_paths = set(file_paths)

    # Generate AppleScript
    script = 'set targetPaths to {}\n'
    for path in target_paths:
        script += f'set end of targetPaths to "{path}"\n'

    script += '''
tell application "Photos"
    set deletedCount to 0
    set albumPhotos to media items
    repeat with aPhoto in albumPhotos
        try
            set photoPath to path of aPhoto
            if photoPath is not missing value then
                if targetPaths contains photoPath then
                    delete aPhoto
                    set deletedCount to deletedCount + 1
                end if
            end if
        end try
    end repeat
    return deletedCount
end tell
'''
    # Write to file
    script_dir = os.path.dirname(file_paths[0]) if file_paths else "."
    # Put script next to the plan file
    plan_dir = os.path.dirname(os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..")))
    # Use current working directory
    import tempfile
    script_path = os.path.join(tempfile.gettempdir(),
                               "snaptidy_photos_trash.applescript")
    with open(script_path, "w", encoding="utf-8") as f:
        f.write(script)

    msg = (
        f"⚠️  ScriptingBridge cannot access Photos.app (permission issue).\n"
        f"   Generated AppleScript: {script_path}\n"
        f"   Run in Terminal: osascript {script_path}\n"
        f"   This will move {len(file_paths)} photos to Photos.app's "
        f'"Recently Deleted" (recoverable for 30 days).'
    )
    return 0, len(file_paths), [msg], set()


def apply_plan(plan_path: str, log_path: str, mode: str = "move"):
    """Apply the move plan.  mode: 'move', 'trash', or 'photos-trash'."""
    log_entries = []
    stats = {"moved": 0, "trashed": 0, "photos_trashed": 0, "skipped": 0, "error": 0}

    # For photos-trash mode, collect all paths first for batch processing
    if mode == "photos-trash":
        photos_paths = []
        with open(plan_path, newline="", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                src = row.get("source_path", "")
                if src and os.path.exists(src):
                    photos_paths.append(src)

        if photos_paths:
            print(f"Processing {len(photos_paths)} files via Photos.app...")
            success, errors, messages, deleted_filenames = move_photos_to_trash(photos_paths)
            stats["photos_trashed"] = success
            stats["error"] = errors
            timestamp = datetime.now().isoformat()
            for path in photos_paths:
                basename = os.path.basename(path)
                # Determine per-file status based on deleted filenames
                is_deleted = basename in deleted_filenames
                log_entries.append({
                    "timestamp": timestamp,
                    "action": "photos-trash",
                    "source_path": path,
                    "target_path": "Photos_Trash",
                    "reason": "Photos.app managed file",
                    "status": "photos_trashed" if is_deleted else "error",
                    "message": "; ".join(messages) if messages and not is_deleted else "",
                })
        else:
            print("No files to process via Photos.app.")
    else:
        # Standard mode: move or trash
        with open(plan_path, newline="", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                action = row.get("action", "").lower()
                src = row.get("source_path")
                dest = row.get("target_path", "")
                reason = row.get("reason", "")
                timestamp = datetime.now().isoformat()
                status = "skipped"
                msg = ""

                if action not in ("move", "trash"):
                    msg = f"Unsupported action: {action}"
                elif not os.path.exists(src):
                    msg = "source missing"
                elif mode == "trash" or action == "trash" or (dest and "__TRASH__" in dest):
                    # Move to macOS Trash
                    success, err = move_to_trash(src)
                    if success:
                        status = "trashed"
                        stats["trashed"] += 1
                    else:
                        status = "error"
                        msg = err
                        stats["error"] += 1
                else:
                    # Regular move
                    os.makedirs(os.path.dirname(dest), exist_ok=True)
                    if os.path.exists(dest):
                        msg = "target exists"
                    else:
                        try:
                            shutil.move(src, dest)
                            status = "moved"
                            stats["moved"] += 1
                        except Exception as e:
                            msg = str(e)
                            status = "error"
                            stats["error"] += 1

                if status == "skipped":
                    stats["skipped"] += 1

                log_entries.append({
                    "timestamp": timestamp,
                    "action": action,
                    "source_path": src,
                    "target_path": dest if mode != "trash" else "macOS_Trash",
                    "reason": reason,
                    "status": status,
                    "message": msg,
                })

    # Write log
    with open(log_path, "w", newline="", encoding="utf-8-sig") as lf:
        fieldnames = ["timestamp", "action", "source_path", "target_path", "reason", "status", "message"]
        writer = csv.DictWriter(lf, fieldnames=fieldnames)
        writer.writeheader()
        for entry in log_entries:
            writer.writerow(entry)

    # Print summary
    print(f"Move plan applied.  Log written to {log_path}")
    parts = []
    if stats["moved"]:
        parts.append(f"Moved: {stats['moved']}")
    if stats["trashed"]:
        parts.append(f"Trashed: {stats['trashed']}")
    if stats["photos_trashed"]:
        parts.append(f"Photos Trashed: {stats['photos_trashed']}")
    parts.append(f"Skipped: {stats['skipped']}")
    parts.append(f"Errors: {stats['error']}")
    print(f"  {'  |  '.join(parts)}")


def compute_file_checksum(path: str) -> str:
    """Compute SHA-256 checksum of a file for undo verification."""
    import hashlib
    try:
        h = hashlib.sha256()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return ""


def save_undo_record(log_entries: list, plan_path: str) -> str:
    """Save undo record for the most recent operation.

    Undo records are stored in the same directory as the plan file,
    under an undo_records/ subdirectory. Each record is a JSON file
    containing all source/destination mappings and file checksums.

    Returns the path to the undo record file.
    """
    undo_dir = os.path.join(os.path.dirname(plan_path), "undo_records")
    os.makedirs(undo_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    undo_path = os.path.join(undo_dir, f"undo_{timestamp}.json")

    # Build undo record
    record = {
        "created_at": datetime.now().isoformat(),
        "expires_at": (datetime.now() + __import__("datetime").timedelta(days=30)).isoformat(),
        "plan_file": os.path.basename(plan_path),
        "operations": [],
    }

    for entry in log_entries:
        if entry.get("status") in ("moved", "trashed"):
            op = {
                "source_path": entry.get("source_path", ""),
                "target_path": entry.get("target_path", ""),
                "action": entry.get("action", ""),
                "status": entry.get("status", ""),
            }
            record["operations"].append(op)

    with open(undo_path, "w", encoding="utf-8") as f:
        __import__("json").dump(record, f, indent=2, ensure_ascii=False)

    return undo_path


def undo_last(plan_dir: str) -> None:
    """Undo the most recent move operation.

    Reads the latest undo record and reverses all operations.
    """
    import json as json_mod

    undo_dir = os.path.join(plan_dir, "undo_records")
    if not os.path.isdir(undo_dir):
        print("No undo records found.")
        return

    # Find latest undo record
    undo_files = sorted(
        [f for f in os.listdir(undo_dir) if f.startswith("undo_") and f.endswith(".json")],
        reverse=True
    )

    if not undo_files:
        print("No undo records found.")
        return

    latest = os.path.join(undo_dir, undo_files[0])
    with open(latest, encoding="utf-8") as f:
        record = json_mod.load(f)

    # Check expiry
    expires = record.get("expires_at", "")
    if expires:
        try:
            exp_dt = datetime.fromisoformat(expires)
            if datetime.now() > exp_dt:
                print(f"⚠️  Undo record expired on {expires}")
                print("   The original files may have been modified. Proceed with caution.")
        except ValueError:
            pass

    ops = record.get("operations", [])
    if not ops:
        print("Undo record contains no operations.")
        return

    print(f"Undo record: {undo_files[0]}")
    print(f"  Created: {record.get('created_at', 'unknown')}")
    print(f"  Operations: {len(ops)}")
    print()

    reversed_count = 0
    error_count = 0

    for op in reversed(ops):  # Reverse order: undo last operation first
        src = op.get("source_path", "")
        dest = op.get("target_path", "")
        status = op.get("status", "")

        if status == "moved" and dest and os.path.exists(dest):
            # Move file back
            try:
                os.makedirs(os.path.dirname(src), exist_ok=True)
                if not os.path.exists(src):
                    shutil.move(dest, src)
                    reversed_count += 1
                else:
                    error_count += 1
            except Exception as e:
                print(f"  ❌ Failed to undo {dest} → {src}: {e}")
                error_count += 1
        elif status == "trashed":
            # Cannot undo macOS Trash from CLI — user must use Finder > Put Back
            print(f"  ⚠️  Cannot undo Trash for {src} — use Finder > Put Back")

    # Remove the undo record after successful undo
    if error_count == 0:
        os.remove(latest)
        print(f"✅ Undone {reversed_count} operations. Undo record removed.")
    else:
        print(f"⚠️  Undone {reversed_count}/{len(ops)} operations. {error_count} errors.")
        print(f"   Undo record kept: {latest}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Apply a move plan for duplicate files (safe: move or trash)")
    parser.add_argument("--plan", required=True, help="Path to move_plan.csv")
    parser.add_argument("--mode", choices=["move", "trash", "photos-trash"], default="move",
                        help="Action mode: 'move' to review folder, 'trash' to macOS Trash, "
                             "'photos-trash' for Photos.app managed files (default: move)")
    parser.add_argument("--undo", action="store_true",
                        help="Undo the most recent move operation")
    args = parser.parse_args()
    plan_path = os.path.abspath(args.plan)
    log_path = os.path.join(os.path.dirname(plan_path), "move_log.csv")

    # Undo mode
    if args.undo:
        plan_dir = os.path.dirname(plan_path)
        # If plan file doesn't exist but directory does, use directory
        if not os.path.isfile(plan_path) and os.path.isdir(plan_dir):
            undo_last(plan_dir)
        else:
            undo_last(os.path.dirname(plan_path))
        return

    print(f"⚠️  About to apply move plan: {plan_path}")
    print(f"   Mode: {args.mode}")
    if args.mode == "trash":
        print("   Files will be moved to macOS Trash (recoverable via Finder)")
    elif args.mode == "photos-trash":
        print("   Files will be removed from Photos.app via PyObjC")
        if not PYOBJC_AVAILABLE:
            print("   ❌ PyObjC not available — install with: pip install pyobjc-framework-Photos")
            print("   Falling back to file-system Trash mode...")
    else:
        print("   Files will be moved to review folder (NOT deleted)")
    print()

    apply_plan(plan_path, log_path, mode=args.mode)

    # Save undo record for non-undo operations
    if not args.undo:
        try:
            from apply_move_plan import save_undo_record
            # Re-read log entries to build undo record
            log_entries_for_undo = []
            with open(log_path, newline="", encoding="utf-8-sig") as lf:
                reader = csv.DictReader(lf)
                for row in reader:
                    log_entries_for_undo.append(row)
            undo_path = save_undo_record(log_entries_for_undo, plan_path)
            print(f"  Undo record saved: {undo_path}")
            print(f"  To undo: python3 scripts/apply_move_plan.py --plan {plan_path} --undo")
        except Exception as e:
            print(f"  ⚠️  Could not save undo record: {e}")


if __name__ == "__main__":
    main()
